keboola_salesforce_extractor_homepage:
    path: '/hello/{name}'
    defaults:
        _controller: 'KeboolaSalesforceExtractorBundle:Default:index'
keboola_sfdc_extractor_configs_list:
    pattern: /configs
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:get'
    requirements:
        _method: GET
keboola_sfdc_extractor_configs_add:
    pattern: /configs
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:post'
    requirements:
        _method: POST
keboola_sfdc_extractor_configs_delete:
    pattern: '/configs/{id}'
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:delete'
    requirements:
        _method: DELETE
keboola_sfdc_extractor_configs_getconfig:
    pattern: '/configs/{id}'
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:getConfig'
    requirements:
        _method: GET
keboola_sfdc_extractor_configs_addrow:
    pattern: '/configs/{id}/rows'
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:addRow'
    requirements:
        _method: POST
keboola_sfdc_extractor_configs_addrowid:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:addRow'
    requirements:
        _method: POST
keboola_sfdc_extractor_configs_getrow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:getRow'
    requirements:
        _method: GET
keboola_sfdc_extractor_configs_deleterow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:deleteRow'
    requirements:
        _method: DELETE
keboola_sfdc_extractor_configs_updaterow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:addRow'
    requirements:
        _method: PUT
keboola_sfdc_extractor_configs_addcreds:
    pattern: '/configs/{id}/credentials'
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:Configs:addAttrs'
    requirements:
        _method: POST
keboola_sfdc_extractor_oauth:
    pattern: /oauth
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:OAuth:getOAuth'
    requirements:
        _method: POST
keboola_sfdc_extractor_oauth_external:
    pattern: /oauth
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:OAuth:externalAuth'
    requirements:
        _method: GET
keboola_sfdc_extractor_oauth_callback:
    pattern: /oauth-callback
    defaults:
        _controller: 'KeboolaSfdcExtractorBundle:OAuth:getOAuthCallback'
